### ISSUE TITLE
Errors from Yabeda in environment where we do not run Yabeda.configure!

### ISSUE THREAD

**Issue by mkimClio** [yabeda-rb/yabeda-anycable#2]
In our test environment, we do not want to collect metrics so we intentionally do not run `Yabeda.configure!`. However, we get errors from Yabeda because it is still in the middleware chain. It looks like [here](https://github.com/yabeda-rb/yabeda-anycable/blob/master/lib/yabeda/anycable.rb#L18-L21) Yabeda is added to the middleware chain before configure. There needs to be a way to add the gem but also not run Yabeda in a specified environment.

**Comment by Envek** [comment]
Postponed middleware insertion until Yabeda is configured and released in [v0.1.1](https://github.com/yabeda-rb/yabeda-anycable/releases/tag/v0.1.1), enjoy!

Quick smoke test shows that AnyCable RPC process is fine with that: metrics are being collected and exposed.

Please also note that [yabeda-sidekiq](https://github.com/yabeda-rb/yabeda-sidekiq) most probably will also need the same change if you're using it as it [also injects middlewares to Sidekiq before Yabeda is configured, outside of `Yabeda.configure` block](https://github.com/yabeda-rb/yabeda-sidekiq/blob/22c545abc8f52f249bcd73eac2893f8f335b8e69/lib/yabeda/sidekiq.rb#L88-L101). (I need to test whether Sidekiq works if middlewares inserted late).
